export { default as Home } from './Home'
export { default as Auth } from './Auth'
export { default as New } from './New'
export { default as User } from './User'
export { default as Posts } from './Posts'
export { default as Bingo } from './Bingo'
export { default as NotFound } from './NotFound'